import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Inspiratia - Test",
  description: "Generated by create next app",
  icons: {
    icon: "/public/inspiratia.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
      <main className="flex w-screen h-screen">
        <section className="w-1/8 text-white font-bold min-w-48" style={{backgroundColor: "rgb(61 89 168)"}}>          
          <div className="p-3 pt-6">
            <Image src="/inspiratia_logo.svg" alt="Description" width={200} height={100} />
          </div>
          <div className="text-lightgray font-bold p-3 text-center">
            <Link href="#">Users</Link>
          </div>
        </section>
        <section className="flex-1 bg-stone-100 flex flex-col min-w-0">
          <nav className="w-full bg-gray-300 p-3 text-gray-800 text-end">
            Hello, <span className="font-bold">User</span>
          </nav>
          <div className="p-5 flex-1 overflow-auto">
            <div className="bg-white p-5 rounded-lg shadow-md w-full h-full">
              {children}
            </div>
          </div>
        </section>
      </main>  
        
        
      </body>
    </html>
  );
}
