import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";
import Provider from "@/app/_components/Providers";
import Header from "@/app/_components/Header";
import Sidebar from "@/app/_components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Inspiratia - Test",
  description: "Generated by create next app",
  icons: {
    icon: "/public/inspiratia.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
      <main className="flex w-screen h-screen">
        <Provider>
          <Sidebar />          
          <section className="flex-1 bg-stone-100 flex flex-col min-w-0">
            <Header />
            <div className="p-5 flex-1 overflow-auto">
              <div className="bg-white p-5 rounded-lg shadow-md w-full h-full">
                {children}
              </div>
            </div>
          </section>
        </Provider>
      </main>  
        
        
      </body>
    </html>
  );
}
